import type { Task } from "../types";

const seedTasks: Task[] = [
  {
    id: "tl_001",
    title: "Classify product images for retail catalog",
    instructions:
      "Look at each product image and tag the primary color, category, and whether the background is clean white.",
    reward: 0.5,
    currency: "USDC",
    required: 50,
    status: "paid",
    createdAt: "2025-05-12T09:24:00Z",
    updatedAt: "2025-05-12T11:20:00Z",
    telegramDelivered: 50,
    distribution: {
      channel: "telegram",
      message:
        "TaskLoop task: Classify product images for retail catalog\n\nLook at each product image and tag the primary color, category, and whether the background is clean white.\n\nReward: 0.5 USDC\nResponses needed: 50",
      source: "mock",
      messageId: "tgmsg_seed_001",
      recipientCount: 50,
      simulated: true,
      sentAt: "2025-05-12T09:30:00Z",
    },
    submissions: [
      {
        id: "s1",
        user: "Maya Chen",
        handle: "@maya_c",
        response: "Color: navy. Category: footwear. Background: clean.",
        submittedAt: "2025-05-12T11:02:00Z",
        validation: "approved",
        validationScore: 0.95,
        validationReason: "Response matches the requested format and criteria.",
        payout: "paid",
        payoutId: "payout_seed_001",
        txHash: "a3f1...9d2c",
      },
      {
        id: "s2",
        user: "Diego Alvarez",
        handle: "@dgo",
        response: "Color: red. Category: apparel. Background: not clean.",
        submittedAt: "2025-05-12T11:14:00Z",
        validation: "approved",
        validationScore: 0.92,
        validationReason: "Response matches the requested format and criteria.",
        payout: "paid",
        payoutId: "payout_seed_002",
        txHash: "b7e2...4a18",
      },
    ],
    payouts: [
      {
        id: "payout_seed_001",
        taskId: "tl_001",
        submissionId: "s1",
        amount: 0.5,
        currency: "USDC",
        provider: "stellar-testnet-mock",
        status: "paid",
        createdAt: "2025-05-12T11:03:00Z",
        processedAt: "2025-05-12T11:03:10Z",
        txHash: "a3f1...9d2c",
      },
      {
        id: "payout_seed_002",
        taskId: "tl_001",
        submissionId: "s2",
        amount: 0.5,
        currency: "USDC",
        provider: "stellar-testnet-mock",
        status: "paid",
        createdAt: "2025-05-12T11:15:00Z",
        processedAt: "2025-05-12T11:15:08Z",
        txHash: "b7e2...4a18",
      },
    ],
  },
  {
    id: "tl_002",
    title: "Verify business addresses in Lisbon",
    instructions:
      "Open the provided Google Maps link and confirm the business name on the storefront matches the listing.",
    reward: 1.2,
    currency: "USDC",
    required: 25,
    status: "submitted",
    createdAt: "2025-05-14T16:10:00Z",
    updatedAt: "2025-05-15T08:41:00Z",
    telegramDelivered: 25,
    distribution: {
      channel: "telegram",
      message:
        "TaskLoop task: Verify business addresses in Lisbon\n\nOpen the provided Google Maps link and confirm the business name on the storefront matches the listing.\n\nReward: 1.2 USDC\nResponses needed: 25",
      source: "mock",
      messageId: "tgmsg_seed_002",
      recipientCount: 25,
      simulated: true,
      sentAt: "2025-05-14T16:12:00Z",
    },
    submissions: [
      {
        id: "s3",
        user: "Ana Ribeiro",
        handle: "@anar",
        response: "Confirmed. Sign reads exactly as listing.",
        submittedAt: "2025-05-15T08:41:00Z",
        validation: "pending",
        payout: "pending",
      },
    ],
    payouts: [],
  },
  {
    id: "tl_003",
    title: "Translate 20 short customer reviews to English",
    instructions: "Translate each review preserving tone. Flag anything you can't confidently translate.",
    reward: 2,
    currency: "USDC",
    required: 10,
    status: "sent",
    createdAt: "2025-05-15T07:55:00Z",
    updatedAt: "2025-05-15T08:00:00Z",
    telegramDelivered: 10,
    distribution: {
      channel: "telegram",
      message:
        "TaskLoop task: Translate 20 short customer reviews to English\n\nTranslate each review preserving tone. Flag anything you can't confidently translate.\n\nReward: 2 USDC\nResponses needed: 10",
      source: "mock",
      messageId: "tgmsg_seed_003",
      recipientCount: 10,
      simulated: true,
      sentAt: "2025-05-15T08:00:00Z",
    },
    submissions: [],
    payouts: [],
  },
  {
    id: "tl_004",
    title: "Rate AI assistant responses for helpfulness",
    instructions: "Score 1–5 and give a one-line reason. Skip anything offensive.",
    reward: 0.25,
    currency: "USDC",
    required: 100,
    status: "created",
    createdAt: "2025-05-15T10:02:00Z",
    updatedAt: "2025-05-15T10:02:00Z",
    telegramDelivered: 0,
    submissions: [],
    payouts: [],
  },
];

export function getDemoTasksSeed(): Task[] {
  return JSON.parse(JSON.stringify(seedTasks)) as Task[];
}
