/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppTasksNewRouteImport } from './routes/_app.tasks.new'
import { Route as AppTasksTaskIdRouteImport } from './routes/_app.tasks.$taskId'
import { Route as AppTasksTaskIdEditRouteImport } from './routes/_app.tasks.$taskId.edit'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksNewRoute = AppTasksNewRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksTaskIdRoute = AppTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksTaskIdEditRoute = AppTasksTaskIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppTasksTaskIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/tasks/$taskId': typeof AppTasksTaskIdRouteWithChildren
  '/tasks/new': typeof AppTasksNewRoute
  '/tasks/$taskId/edit': typeof AppTasksTaskIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/tasks/$taskId': typeof AppTasksTaskIdRouteWithChildren
  '/tasks/new': typeof AppTasksNewRoute
  '/tasks/$taskId/edit': typeof AppTasksTaskIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/tasks/$taskId': typeof AppTasksTaskIdRouteWithChildren
  '/_app/tasks/new': typeof AppTasksNewRoute
  '/_app/tasks/$taskId/edit': typeof AppTasksTaskIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tasks/$taskId' | '/tasks/new' | '/tasks/$taskId/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tasks/$taskId' | '/tasks/new' | '/tasks/$taskId/edit'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/tasks/$taskId'
    | '/_app/tasks/new'
    | '/_app/tasks/$taskId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/new': {
      id: '/_app/tasks/new'
      path: '/tasks/new'
      fullPath: '/tasks/new'
      preLoaderRoute: typeof AppTasksNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/$taskId': {
      id: '/_app/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof AppTasksTaskIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/$taskId/edit': {
      id: '/_app/tasks/$taskId/edit'
      path: '/edit'
      fullPath: '/tasks/$taskId/edit'
      preLoaderRoute: typeof AppTasksTaskIdEditRouteImport
      parentRoute: typeof AppTasksTaskIdRoute
    }
  }
}

interface AppTasksTaskIdRouteChildren {
  AppTasksTaskIdEditRoute: typeof AppTasksTaskIdEditRoute
}

const AppTasksTaskIdRouteChildren: AppTasksTaskIdRouteChildren = {
  AppTasksTaskIdEditRoute: AppTasksTaskIdEditRoute,
}

const AppTasksTaskIdRouteWithChildren = AppTasksTaskIdRoute._addFileChildren(
  AppTasksTaskIdRouteChildren,
)

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppTasksTaskIdRoute: typeof AppTasksTaskIdRouteWithChildren
  AppTasksNewRoute: typeof AppTasksNewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppTasksTaskIdRoute: AppTasksTaskIdRouteWithChildren,
  AppTasksNewRoute: AppTasksNewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
